# -*- mode:makefile; mode:font-lock -*-
# Time-stamp: <21 Jan 2020, 23:00:43 GMT (doug: a14019.essex.ac.uk): Makefile>
texfile = poems
htmldirectory = .
defaulttarget = webpage
html-method = hyperlatex
synctex=0
include ~/LaTeX/Maketex/Makefile
include ../genericMakefile
webpageurl := http://dougarnold.paperplane.io/poems/

