# -*- mode:makefile; mode:font-lock -*-
# Time-stamp: <5 Mar 2020, 22:08:08 GMT (doug: a14019.essex.ac.uk): Makefile>
texfile = poems
htmldirectory = .
defaulttarget = html git
html-method = hyperlatex
synctex=0
include ~/LaTeX/Maketex/Makefile
include ../genericMakefile
# webpageurl := http://dougarnold.paperplane.io/poems/
webpageurl :=  https://dougarnold02.github.io/poems/

