# -*- mode:makefile; mode:font-lock -*-
# Time-stamp: <15:10:03, February 04 2011; Makefile (doug, llmac2.essex.ac.uk)>
include ~/LaTeX/Maketex/dummyindexMakefile
include ../genericMakefile
index.pdf : ~/teaching/FrHackersNotes/handout.pdf
	cp $< $@
