# -*- mode:makefile; mode:font-lock -*-
# Time-stamp: <8 Aug 2003 (doug: S3453.essex.ac.uk): Makefile>
texfile = index
defaulttarget = html
htmldirectory = .
include ~/LaTeX/Maketex/Makefile

include ../../genericMakefile
